name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential nasm xorriso grub-pc-bin grub-common gcc-multilib gdb-multiarch qemu-system-x86 mtools
          sudo apt install -y gcc-13-i686-linux-gnu g++-13-i686-linux-gnu
          sudo apt install -y gcc-13 g++-13

      - name: Build kernel and ISO
        run: make

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: volkmanos-iso
          path: iso/volkmanos.iso
